# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix Product in RcppArmadillo.
#'
#' @param m numeric matrix
#' @param v numeric vector
#' @return matrix product of m and v
#' @export
arma_mv <- function(m, v) {
    .Call(`_sgs_arma_mv`, m, v)
}

#' Matrix Product in RcppArmadillo.
#'
#' @param m numeric sparse matrix
#' @param v numeric vector
#' @return matrix product of m and v
#' @export
arma_sparse <- function(m, v) {
    .Call(`_sgs_arma_sparse`, m, v)
}

